version: "3.8"

services:
  trading_server:
    build: .
    container_name: trading_server
    restart: always
    ports:
      - "5002:5002"
    command: ["python", "trading_server.py"]

  ai_trade_analysis:
    build: .
    container_name: ai_trade_analysis
    restart: always
    ports:
      - "5005:5005"
    command: ["python", "ai_trade_analysis.py"]
